language: java
jdk:
  - oraclejdk8
sudo: false
env:
  matrix:
  - TERM=dumb
services:
  - postgresql
before_script:
  - psql -c 'create database account_manager;' -U postgres
  - chmod a+x gradlew
after_success:
  - ./gradlew jacocoRootReport coveralls
  - bash <(curl -s https://codecov.io/bash)
script:
  - ./gradlew build jacocoTestReport
  - ./gradlew jacocoTestReport